// Bookora Core Single Page Application Router & Lifecycle Controller
import { state } from './state.js';
import { renderHeader, initHeaderEvents } from './components/Header.js';
import { renderFooter } from './components/Footer.js';
import { BookoraAI } from './components/BookoraAIEnhanced.js';
import { Toast } from './components/Toast.js';
import { ReaderModal } from './components/ReaderModal.js';
import { renderHomePage, initHomePageEvents } from './pages/HomePage.js';
import { renderExplorePage, initExploreEvents } from './pages/ExplorePage.js';
import { renderCategoryPage } from './pages/CategoryPage.js';
import { renderCategoriesDirectoryPage, renderCuratedCatalogPage } from './pages/PublicDiscoveryPages.js';
import { renderSearchPage } from './pages/SearchPage.js';
import { renderBookDetailPage, initBookDetailEvents } from './pages/BookDetailPage.js';
import { renderPricingPage, initPricingEvents } from './pages/PricingPage.js';
import { renderSubscriptionManagePage, initSubscriptionManageEvents } from './pages/SubscriptionManagePage.js';
import { renderStaticPage } from './pages/StaticPages.js';
import { renderDashboardPage, initDashboardEvents } from './pages/DashboardPage.js';
import { renderLibraryPage, initLibraryEvents } from './pages/LibraryPage.js';
import { renderOrdersPage } from './pages/OrdersPage.js?v=20260821-2';
import { renderWishlistPage } from './pages/WishlistPage.js';
import { renderCheckoutPage, initCheckoutEvents } from './pages/CheckoutPage.js';
import { renderPaymentSuccessPage } from './pages/PaymentSuccessPage.js?v=20260821-4';
import { renderPaymentFailedPage } from './pages/PaymentFailedPage.js';
import { renderCreatorDashboardPage, initCreatorDashboardEvents } from './pages/CreatorDashboardPage.js';
import { renderPublishInternalPage, initPublishInternalEvents } from './pages/PublishInternalPage.js';
import { renderPublishExternalPage, initPublishExternalEvents } from './pages/PublishExternalPage.js';
import { renderSellerApplyPage, initSellerApplyEvents } from './pages/SellerApplyPage.js';
import { renderSellerSettingsPage, initSellerSettingsEvents } from './pages/SellerSettingsPage.js';
import { renderAdminDashboardPage, initAdminDashboardEvents } from './pages/AdminDashboardPage.js';
import { renderAdminUsersPage, initAdminUsersPageEvents } from './pages/AdminUsersPage.js';
