// Bookora i18n runtime
// - Persists the user's language in Firestore users/{firebaseUid}.language
// - Restores the language after future sign-ins/visits
// - Translates dynamically rendered UI text without changing business data
// - English is always the safe fallback for missing strings
import { state } from './state.js';

const STORAGE_KEY = 'bookora_language';
const DEFAULT_LANGUAGE = 'en';

export const BOOKORA_LANGUAGES = {
  en:{name:'English',native:'English'},hi:{name:'Hindi',native:'हिन्दी'},gu:{name:'Gujarati',native:'ગુજરાતી'},mr:{name:'Marathi',native:'मराठी'},bn:{name:'Bengali',native:'বাংলা'},ta:{name:'Tamil',native:'தமிழ்'},te:{name:'Telugu',native:'తెలుగు'},kn:{name:'Kannada',native:'ಕನ್ನಡ'},ml:{name:'Malayalam',native:'മലയാളം'},pa:{name:'Punjabi',native:'ਪੰਜਾਬੀ'},ur:{name:'Urdu',native:'اردو'},es:{name:'Spanish',native:'Español'},fr:{name:'French',native:'Français'},de:{name:'German',native:'Deutsch'},pt:{name:'Portuguese',native:'Português'},ar:{name:'Arabic',native:'العربية'},ja:{name:'Japanese',native:'日本語'},ko:{name:'Korean',native:'한국어'},zh:{name:'Chinese',native:'中文'},ru:{name:'Russian',native:'Русский'}
};

// Core UI vocabulary. Unknown strings intentionally remain unchanged so no existing
// feature, book metadata, payment text, IDs or user content can be corrupted.
const T = {
  hi:{'Discover. Read. Publish.':'खोजें। पढ़ें। प्रकाशित करें।','Home':'होम','Explore':'एक्सप्लोर','Categories':'श्रेणियाँ','Best Sellers':'बेस्ट सेलर','New Releases':'नई रिलीज़','Trending':'ट्रेंडिंग','Authors':'लेखक','Pricing':'कीमतें','Subscription':'सब्सक्रिप्शन','About':'हमारे बारे में','How It Works':'यह कैसे काम करता है','FAQ':'सामान्य प्रश्न','Contact':'संपर्क','Help':'सहायता','Login':'लॉग इन','Sign Up':'साइन अप','Logout':'लॉग आउट','Profile':'प्रोफ़ाइल','Settings':'सेटिंग्स','Account Settings':'अकाउंट सेटिंग्स','Account Center':'अकाउंट सेंटर','Personal Profile':'व्यक्तिगत प्रोफ़ाइल','Full Name':'पूरा नाम','Email Address':'ईमेल पता','Country / Region':'देश / क्षेत्र','Your Currency':'आपकी मुद्रा','Detect My Region':'मेरा क्षेत्र पहचानें','Language':'भाषा','Timezone':'समय क्षेत्र','Date Format':'दिनांक प्रारूप','Notification Preferences':'सूचना प्राथमिकताएँ','Save Account Preferences':'अकाउंट प्राथमिकताएँ सेव करें','Changes are saved to your Bookora account and reused on future visits.':'आपके बदलाव आपके Bookora अकाउंट में सेव होते हैं और अगली विज़िट में भी लागू रहेंगे।','Order receipts and license delivery emails':'ऑर्डर रसीद और लाइसेंस डिलीवरी ईमेल','Wishlist price reductions & promotions':'विशलिस्ट कीमत में कमी और प्रमोशन','New releases in followed categories':'फॉलो की गई श्रेणियों की नई रिलीज़','Discover inspiring books':'प्रेरणादायक किताबें खोजें','Read Free Sample':'फ्री सैंपल पढ़ें','Buy Now':'अभी खरीदें','Add to Cart':'कार्ट में जोड़ें','Download':'डाउनलोड','Read':'पढ़ें','Search':'खोजें','Save':'सेव करें','Cancel':'रद्द करें','Continue':'जारी रखें','Back':'वापस','Next':'आगे','Previous':'पिछला','Submit':'सबमिट करें','Close':'बंद करें','Loading...':'लोड हो रहा है...','Please sign in first.':'कृपया पहले साइन इन करें।','Region detected. Save your preferences to apply it everywhere.':'क्षेत्र पहचान लिया गया। इसे हर जगह लागू करने के लिए प्राथमिकताएँ सेव करें।'},
  gu:{'Discover. Read. Publish.':'શોધો. વાંચો. પ્રકાશિત કરો.','Home':'હોમ','Explore':'એક્સપ્લોર','Categories':'શ્રેણીઓ','Best Sellers':'બેસ્ટ સેલર','New Releases':'નવી રિલીઝ','Trending':'ટ્રેન્ડિંગ','Authors':'લેખકો','Pricing':'કિંમતો','Subscription':'સબ્સ્ક્રિપ્શન','About':'અમારા વિશે','How It Works':'આ કેવી રીતે કામ કરે છે','FAQ':'સામાન્ય પ્રશ્નો','Contact':'સંપર્ક','Help':'મદદ','Login':'લૉગિન','Sign Up':'સાઇન અપ','Logout':'લૉગઆઉટ','Profile':'પ્રોફાઇલ','Settings':'સેટિંગ્સ','Account Settings':'એકાઉન્ટ સેટિંગ્સ','Account Center':'એકાઉન્ટ સેન્ટર','Personal Profile':'વ્યક્તિગત પ્રોફાઇલ','Full Name':'પૂરું નામ','Email Address':'ઇમેઇલ સરનામું','Country / Region':'દેશ / પ્રદેશ','Your Currency':'તમારી ચલણ','Detect My Region':'મારો પ્રદેશ શોધો','Language':'ભાષા','Timezone':'સમય ઝોન','Date Format':'તારીખ ફોર્મેટ','Notification Preferences':'સૂચના પસંદગીઓ','Save Account Preferences':'એકાઉન્ટ પસંદગીઓ સાચવો','Read Free Sample':'મફત સેમ્પલ વાંચો','Buy Now':'હમણાં ખરીદો','Add to Cart':'કાર્ટમાં ઉમેરો','Download':'ડાઉનલોડ','Read':'વાંચો','Search':'શોધો','Save':'સાચવો','Cancel':'રદ કરો','Continue':'ચાલુ રાખો','Back':'પાછળ','Next':'આગળ','Previous':'પહેલાં','Submit':'સબમિટ કરો','Close':'બંધ કરો','Loading...':'લોડ થઈ રહ્યું છે...'},
  mr:{'Home':'मुख्यपृष्ठ','Explore':'एक्सप्लोर','Categories':'श्रेणी','Best Sellers':'बेस्ट सेलर','New Releases':'नवीन प्रकाशने','Trending':'ट्रेंडिंग','Authors':'लेखक','Pricing':'किंमत','Subscription':'सबस्क्रिप्शन','About':'आमच्याबद्दल','Contact':'संपर्क','Help':'मदत','Login':'लॉगिन','Sign Up':'साइन अप','Logout':'लॉगआउट','Profile':'प्रोफाइल','Settings':'सेटिंग्ज','Language':'भाषा','Save Account Preferences':'खाते प्राधान्ये जतन करा','Read Free Sample':'मोफत नमुना वाचा','Buy Now':'आता खरेदी करा','Add to Cart':'कार्टमध्ये जोडा','Download':'डाउनलोड','Read':'वाचा','Search':'शोधा','Save':'जतन करा','Cancel':'रद्द करा','Continue':'सुरू ठेवा','Back':'मागे','Next':'पुढे','Close':'बंद करा'},
  es:{'Home':'Inicio','Explore':'Explorar','Categories':'Categorías','Best Sellers':'Más vendidos','New Releases':'Novedades','Trending':'Tendencias','Authors':'Autores','Pricing':'Precios','Subscription':'Suscripción','About':'Acerca de','How It Works':'Cómo funciona','FAQ':'Preguntas frecuentes','Contact':'Contacto','Help':'Ayuda','Login':'Iniciar sesión','Sign Up':'Registrarse','Logout':'Cerrar sesión','Profile':'Perfil','Settings':'Configuración','Language':'Idioma','Save Account Preferences':'Guardar preferencias','Read Free Sample':'Leer muestra gratis','Buy Now':'Comprar ahora','Add to Cart':'Añadir al carrito','Download':'Descargar','Read':'Leer','Search':'Buscar','Save':'Guardar','Cancel':'Cancelar','Continue':'Continuar','Back':'Atrás','Next':'Siguiente','Previous':'Anterior','Submit':'Enviar','Close':'Cerrar','Loading...':'Cargando...'},
  fr:{'Home':'Accueil','Explore':'Explorer','Categories':'Catégories','Best Sellers':'Meilleures ventes','New Releases':'Nouveautés','Trending':'Tendances','Authors':'Auteurs','Pricing':'Tarifs','Subscription':'Abonnement','About':'À propos','How It Works':'Comment ça marche','FAQ':'FAQ','Contact':'Contact','Help':'Aide','Login':'Connexion','Sign Up':'Créer un compte','Logout':'Déconnexion','Profile':'Profil','Settings':'Paramètres','Language':'Langue','Save Account Preferences':'Enregistrer les préférences','Read Free Sample':'Lire un extrait gratuit','Buy Now':'Acheter maintenant','Add to Cart':'Ajouter au panier','Download':'Télécharger','Read':'Lire','Search':'Rechercher','Save':'Enregistrer','Cancel':'Annuler','Continue':'Continuer','Back':'Retour','Next':'Suivant','Previous':'Précédent','Submit':'Envoyer','Close':'Fermer','Loading...':'Chargement...'},
  de:{'Home':'Startseite','Explore':'Entdecken','Categories':'Kategorien','Best Sellers':'Bestseller','New Releases':'Neuerscheinungen','Trending':'Trends','Authors':'Autoren','Pricing':'Preise','Subscription':'Abonnement','About':'Über uns','How It Works':'So funktioniert es','FAQ':'FAQ','Contact':'Kontakt','Help':'Hilfe','Login':'Anmelden','Sign Up':'Registrieren','Logout':'Abmelden','Profile':'Profil','Settings':'Einstellungen','Language':'Sprache','Save Account Preferences':'Einstellungen speichern','Read Free Sample':'Kostenlose Leseprobe','Buy Now':'Jetzt kaufen','Add to Cart':'In den Warenkorb','Download':'Herunterladen','Read':'Lesen','Search':'Suchen','Save':'Speichern','Cancel':'Abbrechen','Continue':'Weiter','Back':'Zurück','Next':'Weiter','Previous':'Zurück','Submit':'Senden','Close':'Schließen','Loading...':'Wird geladen...'},
  pt:{'Home':'Início','Explore':'Explorar','Categories':'Categorias','Best Sellers':'Mais vendidos','New Releases':'Novidades','Trending':'Tendências','Authors':'Autores','Pricing':'Preços','Subscription':'Assinatura','About':'Sobre nós','How It Works':'Como funciona','FAQ':'Perguntas frequentes','Contact':'Contato','Help':'Ajuda','Login':'Entrar','Sign Up':'Cadastrar','Logout':'Sair','Profile':'Perfil','Settings':'Configurações','Language':'Idioma','Save Account Preferences':'Salvar preferências','Read Free Sample':'Ler amostra grátis','Buy Now':'Comprar agora','Add to Cart':'Adicionar ao carrinho','Download':'Baixar','Read':'Ler','Search':'Pesquisar','Save':'Salvar','Cancel':'Cancelar','Continue':'Continuar','Back':'Voltar','Next':'Próximo','Previous':'Anterior','Submit':'Enviar','Close':'Fechar','Loading...':'Carregando...'},
  ar:{'Home':'الرئيسية','Explore':'استكشف','Categories':'الفئات','Best Sellers':'الأكثر مبيعًا','New Releases':'الإصدارات الجديدة','Trending':'الرائج','Authors':'المؤلفون','Pricing':'الأسعار','Subscription':'الاشتراك','About':'من نحن','How It Works':'كيف يعمل','FAQ':'الأسئلة الشائعة','Contact':'اتصل بنا','Help':'المساعدة','Login':'تسجيل الدخول','Sign Up':'إنشاء حساب','Logout':'تسجيل الخروج','Profile':'الملف الشخصي','Settings':'الإعدادات','Language':'اللغة','Save Account Preferences':'حفظ تفضيلات الحساب','Read Free Sample':'قراءة عينة مجانية','Buy Now':'اشتر الآن','Add to Cart':'أضف إلى السلة','Download':'تنزيل','Read':'قراءة','Search':'بحث','Save':'حفظ','Cancel':'إلغاء','Continue':'متابعة','Back':'رجوع','Next':'التالي','Previous':'السابق','Submit':'إرسال','Close':'إغلاق','Loading...':'جارٍ التحميل...'},
  ja:{'Home':'ホーム','Explore':'探索','Categories':'カテゴリー','Best Sellers':'ベストセラー','New Releases':'新着','Trending':'トレンド','Authors':'著者','Pricing':'料金','Subscription':'サブスクリプション','About':'概要','How It Works':'使い方','FAQ':'よくある質問','Contact':'お問い合わせ','Help':'ヘルプ','Login':'ログイン','Sign Up':'新規登録','Logout':'ログアウト','Profile':'プロフィール','Settings':'設定','Language':'言語','Save Account Preferences':'アカウント設定を保存','Read Free Sample':'無料サンプルを読む','Buy Now':'今すぐ購入','Add to Cart':'カートに追加','Download':'ダウンロード','Read':'読む','Search':'検索','Save':'保存','Cancel':'キャンセル','Continue':'続行','Back':'戻る','Next':'次へ','Previous':'前へ','Submit':'送信','Close':'閉じる','Loading...':'読み込み中...'},
  ko:{'Home':'홈','Explore':'탐색','Categories':'카테고리','Best Sellers':'베스트셀러','New Releases':'신간','Trending':'트렌드','Authors':'작가','Pricing':'가격','Subscription':'구독','About':'소개','How It Works':'이용 방법','FAQ':'자주 묻는 질문','Contact':'연락처','Help':'도움말','Login':'로그인','Sign Up':'회원가입','Logout':'로그아웃','Profile':'프로필','Settings':'설정','Language':'언어','Save Account Preferences':'계정 설정 저장','Read Free Sample':'무료 샘플 읽기','Buy Now':'지금 구매','Add to Cart':'장바구니에 추가','Download':'다운로드','Read':'읽기','Search':'검색','Save':'저장','Cancel':'취소','Continue':'계속','Back':'뒤로','Next':'다음','Previous':'이전','Submit':'제출','Close':'닫기','Loading...':'로드 중...'},
  zh:{'Home':'首页','Explore':'探索','Categories':'分类','Best Sellers':'畅销书','New Releases':'新书','Trending':'热门','Authors':'作者','Pricing':'价格','Subscription':'订阅','About':'关于我们','How It Works':'使用方法','FAQ':'常见问题','Contact':'联系我们','Help':'帮助','Login':'登录','Sign Up':'注册','Logout':'退出登录','Profile':'个人资料','Settings':'设置','Language':'语言','Save Account Preferences':'保存账户偏好','Read Free Sample':'阅读免费样章','Buy Now':'立即购买','Add to Cart':'加入购物车','Download':'下载','Read':'阅读','Search':'搜索','Save':'保存','Cancel':'取消','Continue':'继续','Back':'返回','Next':'下一步','Previous':'上一步','Submit':'提交','Close':'关闭','Loading...':'加载中...'},
  ru:{'Home':'Главная','Explore':'Обзор','Categories':'Категории','Best Sellers':'Бестселлеры','New Releases':'Новинки','Trending':'В тренде','Authors':'Авторы','Pricing':'Цены','Subscription':'Подписка','About':'О нас','How It Works':'Как это работает','FAQ':'Частые вопросы','Contact':'Контакты','Help':'Помощь','Login':'Войти','Sign Up':'Регистрация','Logout':'Выйти','Profile':'Профиль','Settings':'Настройки','Language':'Язык','Save Account Preferences':'Сохранить настройки','Read Free Sample':'Читать бесплатный образец','Buy Now':'Купить сейчас','Add to Cart':'Добавить в корзину','Download':'Скачать','Read':'Читать','Search':'Поиск','Save':'Сохранить','Cancel':'Отмена','Continue':'Продолжить','Back':'Назад','Next':'Далее','Previous':'Назад','Submit':'Отправить','Close':'Закрыть','Loading...':'Загрузка...'}
};

let currentLanguage = DEFAULT_LANGUAGE;
const originalText = new WeakMap();
let observer = null;
let applying = false;

function normalizeLanguage(value){const v=String(value||'').toLowerCase().split('-')[0];return BOOKORA_LANGUAGES[v]?v:DEFAULT_LANGUAGE;}
function translateText(value){const raw=String(value||'');const trimmed=raw.trim();if(!trimmed)return raw;const dict=T[currentLanguage]||{};const translated=dict[trimmed];if(translated===undefined)return raw;return raw.replace(trimmed,translated);}
function shouldSkip(node){const p=node.parentElement;if(!p)return true;return ['SCRIPT','STYLE','NOSCRIPT','CODE','PRE','TEXTAREA'].includes(p.tagName)||p.closest('[data-i18n-ignore]');}
function translateNode(root){if(!root||applying)return;applying=true;try{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];let n;while((n=walker.nextNode()))nodes.push(n);for(const textNode of nodes){if(shouldSkip(textNode))continue;if(!originalText.has(textNode))originalText.set(textNode,textNode.nodeValue);const original=originalText.get(textNode);const next=translateText(original);if(textNode.nodeValue!==next)textNode.nodeValue=next;}}finally{applying=false;}}
function restoreAndTranslate(){applying=true;try{document.querySelectorAll('[data-i18n-lang-label]').forEach(el=>{el.textContent=BOOKORA_LANGUAGES[currentLanguage].native;});const root=document.getElementById('app');if(root)translateNode(root);}finally{applying=false;}}

async function saveLanguage(language){
  const lang=normalizeLanguage(language);currentLanguage=lang;
  localStorage.setItem(STORAGE_KEY,lang);
  if(state.currentUser?.uid){
    try{const {db}=await state.getFirebase();await db.collection('users').doc(state.currentUser.uid).set({language:lang,languageUpdatedAt:new Date().toISOString()},{merge:true});state.currentUser={...state.currentUser,language:lang};localStorage.setItem('bookora_user_profile',JSON.stringify(state.currentUser));}
    catch(error){console.warn('[i18n] Firebase language save skipped:',error.message);}
  }
  document.documentElement.lang=lang;
  document.documentElement.dir=lang==='ar'||lang==='ur'?'rtl':'ltr';
  restoreAndTranslate();
}

function populateLanguageSelects(){document.querySelectorAll('#user-set-language').forEach(select=>{const old=select.value;select.innerHTML=Object.entries(BOOKORA_LANGUAGES).map(([code,m])=>`<option value="${code}">${m.native} — ${m.name}</option>`).join('');select.value=BOOKORA_LANGUAGES[currentLanguage]?currentLanguage:(BOOKORA_LANGUAGES[old]?old:DEFAULT_LANGUAGE);select.onchange=()=>saveLanguage(select.value);});}

async function loadPersistedLanguage(){
  let lang=localStorage.getItem(STORAGE_KEY)||'';
  if(state.currentUser?.language)lang=state.currentUser.language;
  if(!lang&&state.currentUser?.uid){try{const {db}=await state.getFirebase();const snap=await db.collection('users').doc(state.currentUser.uid).get();if(snap.exists&&snap.data()?.language)lang=snap.data().language;}catch(error){console.warn('[i18n] Firebase language load skipped:',error.message);}}
  currentLanguage=normalizeLanguage(lang||navigator.language||DEFAULT_LANGUAGE);
  localStorage.setItem(STORAGE_KEY,currentLanguage);
  document.documentElement.lang=currentLanguage;document.documentElement.dir=currentLanguage==='ar'||currentLanguage==='ur'?'rtl':'ltr';
  populateLanguageSelects();restoreAndTranslate();
}

function init(){
  if(observer)return;
  const app=document.getElementById('app');if(!app)return;
  observer=new MutationObserver(mutations=>{if(applying)return;let changed=false;for(const m of mutations){if(m.type==='childList'&&m.addedNodes.length){m.addedNodes.forEach(n=>{if(n.nodeType===Node.ELEMENT_NODE){translateNode(n);changed=true;}});}}if(changed)populateLanguageSelects();});
  observer.observe(app,{childList:true,subtree:true});
  populateLanguageSelects();
  restoreAndTranslate();
  loadPersistedLanguage();
}

state.subscribe(event=>{if(event==='USER_LOGGED_IN'){loadPersistedLanguage();}else if(event==='USER_LOGGED_OUT'){currentLanguage=normalizeLanguage(localStorage.getItem(STORAGE_KEY)||DEFAULT_LANGUAGE);document.documentElement.lang=currentLanguage;document.documentElement.dir='ltr';restoreAndTranslate();}});

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.BookoraI18n={languages:BOOKORA_LANGUAGES,getLanguage:()=>currentLanguage,setLanguage:saveLanguage};
