// Bookora global language runtime.
// Lightweight: never observes the entire document. This keeps the SPA fast.
(() => {
  'use strict';
  if (window.__BOOKORA_LANGUAGE_RUNTIME__) return;
  window.__BOOKORA_LANGUAGE_RUNTIME__ = true;
  const LANGUAGES=[['en','English'],['hi','Hindi'],['gu','Gujarati'],['mr','Marathi'],['bn','Bengali'],['ta','Tamil'],['te','Telugu'],['kn','Kannada'],['ml','Malayalam'],['pa','Punjabi'],['ur','Urdu'],['ar','Arabic'],['es','Spanish'],['fr','French'],['de','German'],['pt','Portuguese'],['it','Italian'],['ru','Russian'],['zh-CN','Chinese (Simplified)'],['zh-TW','Chinese (Traditional)'],['ja','Japanese'],['ko','Korean'],['tr','Turkish'],['id','Indonesian'],['vi','Vietnamese'],['th','Thai'],['nl','Dutch'],['pl','Polish'],['uk','Ukrainian'],['fa','Persian'],['sw','Swahili']];
  const MAP=Object.fromEntries(LANGUAGES.map(([c,n])=>[c,n]));
  const KEY='bookora_language_code',COOKIE='googtrans',DEFAULT='en';
  const getCode=()=>{try{const c=localStorage.getItem(KEY);return MAP[c]?c:DEFAULT;}catch(_){return DEFAULT;}};
  function setCookie(code){if(code===DEFAULT){document.cookie=`${COOKIE}=; path=/; max-age=0; SameSite=Lax`;document.cookie=`${COOKIE}=; path=/Bookora/; max-age=0; SameSite=Lax`;return;}const v=encodeURIComponent(`/en/${code}`);document.cookie=`${COOKIE}=${v}; path=/; max-age=31536000; SameSite=Lax`;document.cookie=`${COOKIE}=${v}; path=/Bookora/; max-age=31536000; SameSite=Lax`;}
  function auth(){try{return window.firebase?.apps?.length?window.firebase.auth():null;}catch(_){return null;}}
  async function saveFirebase(code){const u=auth()?.currentUser;if(!u||!window.firebase?.firestore)return false;try{await window.firebase.firestore().collection('users').doc(u.uid).set({languageCode:code,languageName:MAP[code]||MAP[DEFAULT],languageUpdatedAt:window.firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return true;}catch(_){return false;}}
  function ensureHost(){if(document.getElementById('google_translate_element'))return;const e=document.createElement('div');e.id='google_translate_element';e.setAttribute('aria-hidden','true');e.style.cssText='position:fixed;left:-10000px;top:-10000px;width:1px;height:1px;overflow:hidden;opacity:0;pointer-events:none;z-index:-1;';document.body?.appendChild(e);}
  function initTranslator(){if(!window.google?.translate?.TranslateElement||document.querySelector('.goog-te-gadget'))return;try{new window.google.translate.TranslateElement({pageLanguage:'en',includedLanguages:LANGUAGES.map(x=>x[0]).join(','),autoDisplay:false},'google_translate_element');}catch(_) {}}
  window.googleTranslateElementInit=()=>{ensureHost();initTranslator();};
  function loadTranslator(){if(getCode()===DEFAULT)return;if(window.google?.translate?.TranslateElement){ensureHost();initTranslator();return;}if(document.getElementById('bookora-google-translate-script'))return;const s=document.createElement('script');s.id='bookora-google-translate-script';s.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';s.async=true;document.head.appendChild(s);}
  function setupLanguageSelect(){const select=document.getElementById('user-set-language');if(!select)return false;const current=getCode();const signature=LANGUAGES.map(([c,n])=>`${c}:${n}`).join('|');if(select.dataset.bookoraLanguageOptions!==signature){select.innerHTML=LANGUAGES.map(([c,n])=>`<option value="${c}" ${c===current?'selected':''}>${n}</option>`).join('');select.dataset.bookoraLanguageOptions=signature;}if(select.dataset.bookoraLanguageBound==='1')return true;select.dataset.bookoraLanguageBound='1';select.addEventListener('change',async()=>{const code=MAP[select.value]?select.value:DEFAULT;try{localStorage.setItem(KEY,code);}catch(_){}setCookie(code);select.disabled=true;await saveFirebase(code);window.location.reload();});return true;}
  function start(){if(!document.body)return;setupLanguageSelect();if(getCode()!==DEFAULT)setTimeout(loadTranslator,1500);const retry=setInterval(()=>{if(setupLanguageSelect())clearInterval(retry);},500);setTimeout(()=>clearInterval(retry),10000);window.addEventListener('hashchange',()=>setTimeout(setupLanguageSelect,50));const a=auth();if(a)a.onAuthStateChanged(()=>{if(!a.currentUser||localStorage.getItem(KEY))return;try{window.firebase.firestore().collection('users').doc(a.currentUser.uid).get().then(s=>{const r=String(s.data()?.languageCode||'').trim();if(MAP[r]){localStorage.setItem(KEY,r);setCookie(r);window.location.reload();}}).catch(()=>{});}catch(_) {}});window.BOOKORA_LANGUAGE={languages:LANGUAGES.map(([code,name])=>({code,name})),get:getCode,set:async code=>{if(!MAP[code])return;try{localStorage.setItem(KEY,code);}catch(_){}setCookie(code);await saveFirebase(code);window.location.reload();}};}
  const boot=()=>setTimeout(start,300);if(document.readyState==='loading')window.addEventListener('load',boot,{once:true});else boot();
})();
