import { apiFetch } from '../config.js';
import { updateSEO } from '../utils/seo.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const db=()=>window.firebase?.firestore?window.firebase.firestore():null;
const reviewOf=b=>b?.adminAiReview||b?.admin_ai_review||null;
async function load(){const d=db();if(!d)throw Error('Firebase is not ready.');const s=await d.collection('books').get();return s.docs.map(x=>({id:String(x.id),...x.data()})).filter(b=>String(b.status||'pending').toLowerCase()==='pending');}
async function run(id){const r=await apiFetch('/api/admin/ebook-review/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({book_id:String(id)})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw Error(d.error||`Review failed (HTTP ${r.status})`);return d.review;}
function card(b){const r=reviewOf(b),reasons=Array.isArray(r?.reasons)?r.reasons:[],uid=b.seller_id||b.sellerId||b.creator_id||b.creatorId||'Not available';const rec=String(r?.recommendation||'manual_review').toLowerCase();return `<article class="ars-card"><div><h3>${esc(b.title||'Untitled eBook')}</h3><p>Author: ${esc(b.author||'Unknown')} · Uploader ID: ${esc(uid)}</p><p>Category: ${esc(b.category||'—')} · Book ID: ${esc(b.id)}</p><span class="ars-b ${r?(rec==='approve'?'ok':rec==='reject'?'bad':'manual'):'pending'}">${b.__run?'ANALYZING PDF…':r?`AI RECOMMENDS ${rec.toUpperCase()}`:'AI REVIEW PENDING'}</span>${r?`<div class="ars-report"><b>Summary:</b> ${esc(r.summary||'No summary')}<br><b>Confidence:</b> ${esc(r.confidence??0)}% · <b>Pages:</b> ${esc(r.pageCount??'—')} · <b>Text:</b> ${esc(r.textChars??0)} chars<br><b>Reasons:</b><ul>${reasons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div>${Object.entries(r.checks||{}).map(([k,v])=>`<span><b>${esc(k.replaceAll('_',' '))}:</b> ${esc(v)}</span>`).join(' ')}</div></div>`:'<div class="ars-wait">Dedicated Groq API will inspect the stored PDF.</div>'}</div><div class="ars-actions"><button class="ars-btn ai" data-review="${esc(b.id)}" ${b.__run?'disabled':''}>${b.__run?'Analyzing…':r?'Re-analyze':'Run Groq Review'}</button></div></article>`;}
function styles(){if(document.getElementById('ars-style'))return;const s=document.createElement('style');s.id='ars-style';s.textContent=`.ars-wrap{max-width:1180px;margin:auto;padding:2.5rem 1rem 5rem}.ars-hero,.ars-card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;box-shadow:0 6px 24px rgba(15,23,42,.05)}.ars-hero{padding:24px;margin-bottom:16px}.ars-hero h1{margin:5px 0;color:#0f172a}.ars-hero p,.ars-card p{color:#64748b;font-size:12px;line-height:1.55}.ars-stats{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.ars-stat{padding:8px 11px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:9px;font-size:12px}.ars-btn{border:0;border-radius:8px;padding:9px 11px;font-weight:800;cursor:pointer;background:#f1f5f9}.ars-btn.ai{background:#7c3aed;color:#fff}.ars-btn:disabled{opacity:.55}.ars-list{display:grid;gap:12px}.ars-card{padding:17px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px}.ars-card h3{margin:0;color:#0f172a}.ars-b{display:inline-block;margin-top:7px;padding:5px 8px;border-radius:999px;font-size:9px;font-weight:900}.pending{background:#fef3c7;color:#92400e}.ok{background:#dcfce7;color:#166534}.bad{background:#fee2e2;color:#991b1b}.manual{background:#ede9fe;color:#6d28d9}.ars-report{margin-top:11px;padding:12px;background:#f8fafc;border-radius:10px;color:#475569;font-size:12px;line-height:1.6}.ars-report ul{margin:5px 0 5px 18px}.ars-wait{margin-top:10px;color:#64748b;font-size:11px}.ars-actions{display:flex;gap:7px;align-items:flex-start}.ars-empty{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:50px;text-align:center;color:#64748b}@media(max-width:700px){.ars-card{grid-template-columns:1fr}}`;document.head.appendChild(s);}
export function renderAdminReviewSubmissionsPage(){styles();updateSEO({title:'Review Submissions — Admin',description:'Admin eBook moderation and dedicated Groq review queue.'});return `<main class="ars-wrap"><section class="ars-hero"><div style="font-size:11px;font-weight:900;letter-spacing:.08em;color:#7c3aed">ADMIN MODERATION</div><h1>Review Submissions</h1><p>Every pending eBook appears here. The dedicated Groq API reviews the stored PDF and gives reasons and a recommendation. <b>Only Admin makes the final decision.</b></p><div class="ars-stats"><span class="ars-stat">Pending: <b id="ars-count">—</b></span><span class="ars-stat">AI reviewed: <b id="ars-reviewed">—</b></span><button class="ars-btn" id="ars-refresh">Refresh</button></div></section><section class="ars-list" id="ars-list"><div class="ars-empty">Loading…</div></section></main>`;}
export async function initAdminReviewSubmissionsEvents(){const list=document.getElementById('ars-list');if(!list)return;const draw=xs=>{document.getElementById('ars-count').textContent=xs.length;document.getElementById('ars-reviewed').textContent=xs.filter(x=>!!reviewOf(x)).length;list.innerHTML=xs.length?xs.map(card).join(''):'<div class="ars-empty">✓ No pending eBook submissions right now.</div>';};const refresh=async()=>{try{draw(await load());}catch(e){list.innerHTML=`<div class="ars-empty">${esc(e.message||'Could not load submissions.')}</div>`;}};list.onclick=async e=>{const b=e.target.closest('[data-review]');if(!b)return;const id=b.dataset.review;let xs=await load(),i=xs.findIndex(x=>String(x.id)===String(id));if(i<0)return;xs[i].__run=true;draw(xs);try{await run(id);}catch(err){xs[i].__err=err.message||'Review failed';}finally{await refresh();}};document.getElementById('ars-refresh')?.addEventListener('click',refresh);await refresh();clearInterval(window.__ARS_TIMER);window.__ARS_TIMER=setInterval(()=>{if(String(location.hash).startsWith('#/admin/review-submissions'))refresh();},15000);}
