import { updateSEO } from '../utils/seo.js';
import { API_BASE_URL } from '../config.js';

const API=(window.BOOKORA_API_URL||API_BASE_URL||'https://bookora-backend-x08l.onrender.com').replace(/\/$/,'');
const esc=(v='')=>String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));

function sampleStyles(){
  if(document.getElementById('bookora-free-sample-style'))return;
  const s=document.createElement('style');s.id='bookora-free-sample-style';s.textContent=`
  .bookora-sample-open{overflow:hidden!important}.bs-overlay{position:fixed;inset:0;z-index:9999;background:rgba(15,23,42,.68);backdrop-filter:blur(7px);display:flex;align-items:center;justify-content:center;padding:24px;box-sizing:border-box}.bs-modal{width:min(980px,100%);height:min(94vh,920px);background:#f4f7fb;border-radius:18px;overflow:hidden;box-shadow:0 24px 80px rgba(0,0,0,.3);display:flex;flex-direction:column}.bs-head{height:70px;flex:0 0 70px;background:#fff;border-bottom:1px solid #e2e8f0;display:flex;align-items:center;justify-content:space-between;padding:0 18px}.bs-kicker{font-size:10px;font-weight:900;letter-spacing:.08em;color:#2563eb}.bs-head-title{margin-top:3px;font-size:16px;font-weight:850;color:#0f172a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.bs-actions{display:flex;gap:8px}.bs-icon{width:42px;height:42px;border:1px solid #dbe3ee;border-radius:12px;background:#fff;color:#1e293b;display:grid;place-items:center;cursor:pointer;font-size:20px;font-weight:800}.bs-scroll{overflow:auto;flex:1;padding:20px 18px 30px}.bs-title{text-align:center;margin:0 auto 16px}.bs-title h1{margin:0;font-size:clamp(24px,4vw,36px);line-height:1.08;color:#0b1328}.bs-title p{margin:7px 0 0;color:#64748b;font-size:12px}.bs-pages{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;width:min(780px,100%);margin:auto}.bs-page{background:#fff;border:1px solid #dbe3ee;border-radius:7px;overflow:hidden;box-shadow:0 10px 28px rgba(15,23,42,.1)}.bs-page canvas{display:block;width:100%;height:auto;background:#fff}.bs-loading,.bs-error{grid-column:1/-1;background:#fff;border:1px solid #dbe3ee;border-radius:12px;padding:60px 20px;text-align:center;color:#64748b;font-size:13px;font-weight:800}.bs-error p{color:#64748b;margin:8px 0 18px;font-weight:500}.bs-btn{min-height:40px;padding:0 15px;border-radius:10px;font-size:12px;font-weight:800;background:#fff;color:#334155;border:1px solid #dbe3ee;cursor:pointer}.bs-buybar{margin:18px auto 0;width:min(780px,100%);box-sizing:border-box;background:#fff;border:1px solid #dbe3ee;border-radius:13px;padding:11px 13px;display:flex;align-items:center;justify-content:center;gap:13px}.bs-buy{display:inline-flex;align-items:center;justify-content:center;min-height:39px;padding:0 17px;border-radius:10px;background:#2563eb;color:#fff;text-decoration:none;font-size:12px;font-weight:900}@media(max-width:640px){.bs-overlay{padding:0}.bs-modal{width:100%;height:100%;border-radius:0}.bs-head{height:62px;flex-basis:62px;padding:0 12px}.bs-scroll{padding:14px 8px 22px}.bs-pages{grid-template-columns:1fr;gap:10px}}
  `;document.head.appendChild(s);
}
function base64ToBytes(value){const clean=String(value||'').replace(/^data:application\/pdf;base64,/i,'').replace(/\s/g,'');if(!clean)throw new Error('PREVIEW_DATA_MISSING');const binary=atob(clean),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
export function renderFreeSamplePage(book){const title=book?.title||'eBook Sample';sampleStyles();updateSEO({title:`${title} — Free Sample`,description:`Preview selected sample pages from ${title} on Bookora.`});const slug=encodeURIComponent(book?.slug||book?.id||'');return `<div class="bs-overlay" id="bookora-free-sample-page" role="dialog" aria-modal="true"><div class="bs-modal"><div class="bs-head"><div><div class="bs-kicker">FREE SAMPLE · UP TO 6 PAGES</div><div class="bs-head-title">${esc(title)}</div></div><div class="bs-actions"><button class="bs-icon" id="bookora-sample-back" type="button" aria-label="Back">←</button><button class="bs-icon" id="bookora-sample-close" type="button" aria-label="Close">×</button></div></div><div class="bs-scroll"><header class="bs-title"><h1>${esc(title)}</h1><p>Selected preview pages — the complete PDF is never loaded into the reader.</p></header><section id="bookora-sample-stack" class="bs-pages"><div class="bs-loading">Preparing your free sample…</div></section><div class="bs-buybar"><a class="bs-buy" href="#/checkout/${slug}">Buy Full eBook →</a></div></div></div></div>`;}
function abortActivePreview(overlay){try{overlay?._bookoraPreviewAbort?.abort();}catch(_){}if(overlay)delete overlay._bookoraPreviewAbort;}
export function closeFreeSamplePage(){const overlay=document.getElementById('bookora-free-sample-page');if(overlay){abortActivePreview(overlay);overlay.dataset.closed='1';overlay.remove();}document.body.classList.remove('bookora-sample-open');}
async function requestPreview(book,signal){const key=String(book?.slug||book?.id||'').trim();if(!key)throw new Error('BOOK_ID_MISSING');const response=await fetch(`${API}/api/books/${encodeURIComponent(key)}/sample?mode=selected-6`,{cache:'no-store',headers:{Accept:'application/json'},signal});let payload;try{payload=await response.json();}catch(_){throw new Error(`PREVIEW_INVALID_RESPONSE_HTTP_${response.status}`);}if(!response.ok||payload?.success!==true){const error=new Error(`${payload?.error||`HTTP_${response.status}`}: ${payload?.message||'Preview pages could not be generated.'}`);error.code=payload?.error||`HTTP_${response.status}`;error.status=response.status;throw error;}if(payload.bookId&&String(payload.bookId)!==key&&String(payload.bookId)!==String(book?.id||''))throw new Error('PREVIEW_BOOK_MISMATCH');if(!payload.preview?.data)throw new Error('PREVIEW_DATA_MISSING');return payload;}
async function renderPreview(stack,book,payload,requestId){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:base64ToBytes(payload.preview.data)}).promise;if(requestId!==stack.dataset.requestId){pdf.destroy?.();return;}const count=Math.min(6,pdf.numPages,Number(payload.pageCount||pdf.numPages));if(!count){pdf.destroy?.();throw new Error('PREVIEW_HAS_NO_PAGES');}stack.innerHTML='';const width=Math.min(780,stack.clientWidth||780),ratio=Math.min(window.devicePixelRatio||1,2),frag=document.createDocumentFragment();for(let i=0;i<count;i++){if(requestId!==stack.dataset.requestId){pdf.destroy?.();return;}const page=await pdf.getPage(i+1),base=page.getViewport({scale:1}),vp=page.getViewport({scale:width/base.width}),canvas=document.createElement('canvas');canvas.width=Math.floor(vp.width*ratio);canvas.height=Math.floor(vp.height*ratio);canvas.setAttribute('aria-label',`${book.title||'eBook'} sample page ${i+1}`);await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:vp,transform:ratio!==1?[ratio,0,0,ratio,0,0]:null}).promise;const card=document.createElement('article');card.className='bs-page';card.appendChild(canvas);frag.appendChild(card);page.cleanup?.();}if(requestId!==stack.dataset.requestId){pdf.destroy?.();return;}stack.appendChild(frag);pdf.cleanup?.();pdf.destroy?.();}
async function runPreview(book,overlay){const stack=overlay?.querySelector('#bookora-sample-stack');if(!stack||!book||overlay?.dataset.closed==='1')return;abortActivePreview(overlay);const requestId=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;stack.dataset.requestId=requestId;stack.innerHTML='<div class="bs-loading">Preparing your free sample…</div>';const controller=new AbortController();overlay._bookoraPreviewAbort=controller;try{const payload=await requestPreview(book,controller.signal);if(overlay.dataset.closed==='1'||requestId!==stack.dataset.requestId)return;await renderPreview(stack,book,payload,requestId);}catch(error){if(error?.name==='AbortError'||overlay.dataset.closed==='1'||requestId!==stack.dataset.requestId)return;console.error('[Bookora Free Sample] preview request failed',{bookId:book?.id,slug:book?.slug,error:error?.message,status:error?.status,code:error?.code});stack.innerHTML='<div class="bs-error"><b>Free sample is temporarily unavailable.</b><p>We couldn\'t prepare the selected preview pages right now.</p><button class="bs-btn" id="bs-error-retry" type="button">Try Again</button></div>';stack.querySelector('#bs-error-retry')?.addEventListener('click',()=>runPreview(book,overlay),{once:true});}finally{if(overlay._bookoraPreviewAbort===controller)delete overlay._bookoraPreviewAbort;}}
export async function initFreeSamplePage(book){const overlay=document.getElementById('bookora-free-sample-page');if(!overlay||!book)return;document.body.classList.add('bookora-sample-open');if(!overlay.dataset.listenersAttached){overlay.dataset.listenersAttached='1';document.getElementById('bookora-sample-close')?.addEventListener('click',closeFreeSamplePage);document.getElementById('bookora-sample-back')?.addEventListener('click',closeFreeSamplePage);overlay.addEventListener('click',e=>{if(e.target===overlay)closeFreeSamplePage();});}return runPreview(book,overlay);}
