import { state } from '../state.js';
import { apiFetch } from '../config.js';

const esc = v => String(v ?? '').replace(/[&<>'\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const api = async (path, options = {}) => { const r = await apiFetch(path, options); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || `Request failed (${r.status})`); return d; };
const REVIEW_CACHE_KEY = 'bookora_public_reviews_v1';
const REVIEW_CACHE_TTL = 5 * 60 * 1000;
let cashfreeReady = null;

function preloadCashfree(){
  if(window.Cashfree) return Promise.resolve();
  if(cashfreeReady) return cashfreeReady;
  cashfreeReady = new Promise((resolve,reject)=>{
    const existing = document.querySelector('script[data-bookora-cashfree="1"]');
    if(existing){ existing.addEventListener('load',resolve,{once:true}); existing.addEventListener('error',()=>reject(new Error('Cashfree payment service could not be loaded.')),{once:true}); return; }
    const s=document.createElement('script'); s.src='https://sdk.cashfree.com/js/v3/cashfree.js'; s.async=true; s.dataset.bookoraCashfree='1'; s.onload=resolve; s.onerror=()=>reject(new Error('Cashfree payment service could not be loaded.')); document.head.appendChild(s);
  });
  return cashfreeReady;
}

export function renderReviewSupportPage(){return `<section class="rs-page"><div class="rs-hero"><div><span class="rs-kicker">BOOKORA COMMUNITY</span><h1>Review Bookora &amp; Support Us</h1><p>Your feedback helps us improve. If Bookora is useful to you, you can also voluntarily support its continued development.</p></div><div class="rs-hero-icon">♡</div></div><div class="rs-grid"><article class="rs-card"><div class="rs-card-head"><div><span class="rs-mini">YOUR VOICE</span><h2>Share your review</h2></div><span class="rs-star">★</span></div><form id="rs-review-form"><div class="rs-rating">${[1,2,3,4,5].map(n=>`<button type="button" class="rs-star-btn" data-rating="${n}">★</button>`).join('')}</div><input type="hidden" id="rs-rating" value="5"><select id="rs-category"><option value="overall">Overall Experience</option><option value="design">Website Design</option><option value="books">Books</option><option value="buying">Buying Experience</option><option value="performance">Performance</option><option value="suggestion">Suggestion</option><option value="bug">Bug Report</option></select><textarea id="rs-comment" minlength="10" maxlength="1000" required placeholder="Tell us what you liked or what we can improve..."></textarea><label class="rs-check"><input id="rs-public" type="checkbox" checked> Show my name with this review</label><button class="rs-primary" type="submit">Submit Review</button><div id="rs-review-msg" class="rs-msg"></div></form></article><article class="rs-card"><div class="rs-card-head"><div><span class="rs-mini">OPTIONAL SUPPORT</span><h2>Support Bookora</h2></div><span class="rs-heart">♥</span></div><p class="rs-muted">Choose an amount you are comfortable with. This is completely optional and does not affect your account or access.</p><div class="rs-amounts">${[10,25,50,100].map(v=>`<button type="button" data-amount="${v}">₹${v}</button>`).join('')}</div><div class="rs-custom"><span>₹</span><input id="rs-amount" inputmode="decimal" type="number" min="1" max="100000" step="1" placeholder="Custom amount"></div><input id="rs-phone" inputmode="numeric" maxlength="10" autocomplete="tel" placeholder="10-digit phone number for payment"><button class="rs-primary" id="rs-donate-btn" type="button">Continue to Support</button><div id="rs-donate-msg" class="rs-msg"></div><small class="rs-note">Payments are processed securely through Cashfree. Bookora does not collect card or UPI credentials.</small></article></div><section class="rs-reviews-section" id="rs-reviews-section"><div class="rs-section-title"><div><span class="rs-mini">COMMUNITY FEEDBACK</span><h2>What readers say</h2></div><div id="rs-summary" class="rs-summary"></div></div><div id="rs-reviews" class="rs-reviews-list"><div class="rs-msg">Loading reader reviews…</div></div><div id="rs-reviews-controls" class="rs-reviews-controls" style="display:none"><button type="button" id="rs-view-all" class="rs-view-all">View all reviews</button></div></section></section>`;}

function setRating(v){const n=Math.max(1,Math.min(5,Number(v)||5));const input=document.getElementById('rs-rating');if(input)input.value=n;document.querySelectorAll('.rs-star-btn').forEach(b=>b.classList.toggle('active',Number(b.dataset.rating)<=n));}
let showAllReviews = false;
function validReviews(reviews){return Array.isArray(reviews)?reviews.filter(r=>r&&Number(r.rating)>=1&&Number(r.rating)<=5):[];}
function reviewMarkup(reviews){return reviews.map(r=>`<article class="rs-review"><div class="rs-review-top"><strong>${esc(r.displayName||'Bookora Reader')}</strong><span>${'★'.repeat(Math.max(0,Math.min(5,Number(r.rating)||0)))}${'☆'.repeat(Math.max(0,5-Math.min(5,Number(r.rating)||0)))}</span></div><p>${esc(r.comment)}</p><small>${esc(r.category||'overall')} · ${esc(new Date(r.createdAt||Date.now()).toLocaleDateString('en-IN'))}</small></article>`).join('');}
function renderReviewList(reviews){const list=document.getElementById('rs-reviews'),controls=document.getElementById('rs-reviews-controls'),button=document.getElementById('rs-view-all');if(!list)return;const all=validReviews(reviews),visible=showAllReviews?all:all.slice(0,2);list.innerHTML=visible.length?reviewMarkup(visible):'<div class="rs-msg">No reader reviews yet. Be the first to share your experience.</div>';if(controls&&button){const hasMore=all.length>2;controls.style.display=hasMore?'flex':'none';button.textContent=showAllReviews?'Show less':'View all reviews';button.onclick=()=>{showAllReviews=!showAllReviews;renderReviewList(all);};}}
function readReviewCache(){try{const raw=sessionStorage.getItem(REVIEW_CACHE_KEY);if(!raw)return null;const cached=JSON.parse(raw);if(!cached||Date.now()-Number(cached.savedAt||0)>REVIEW_CACHE_TTL)return null;return cached.data||null;}catch(_){return null;}}
function writeReviewCache(data){try{sessionStorage.setItem(REVIEW_CACHE_KEY,JSON.stringify({savedAt:Date.now(),data}));}catch(_){} }
async function loadReviews(){const section=document.getElementById('rs-reviews-section'),list=document.getElementById('rs-reviews'),s=document.getElementById('rs-summary');if(!section||!list||!s)return;section.style.display='block';const cached=readReviewCache();if(cached){const cachedReviews=validReviews(cached.reviews);s.textContent=cachedReviews.length?`★ ${Number(cached.averageRating||0).toFixed(1)} · ${cachedReviews.length} review${cachedReviews.length===1?'':'s'}`:'No reviews yet';renderReviewList(cachedReviews);}try{const d=await api('/api/reviews');const a=validReviews(d.reviews);writeReviewCache({reviews:a,averageRating:Number(d.averageRating||0)});s.textContent=a.length?`★ ${Number(d.averageRating||0).toFixed(1)} · ${a.length} review${a.length===1?'':'s'}`:'No reviews yet';renderReviewList(a);}catch(error){console.warn('[Bookora reviews] Unable to load public reviews:',error);if(!cached){s.textContent='Reviews are loading';list.innerHTML='<div class="rs-msg">Reader reviews will appear here as soon as the Firebase-backed service responds.</div>';}}section.style.display='block';}

async function saveReviewToBackend(payload){const d=await api('/api/reviews',{method:'POST',body:JSON.stringify({rating:Math.max(1,Math.min(5,Number(payload.rating)||5)),category:String(payload.category||'overall'),comment:String(payload.comment||'').trim(),publicName:payload.publicName!==false})});if(!d.success||!d.reviewId)throw new Error(d.error||'Review could not be saved.');return {reviewId:d.reviewId,rating:Math.max(1,Math.min(5,Number(payload.rating)||5)),category:String(payload.category||'overall'),comment:String(payload.comment||'').trim(),publicName:payload.publicName!==false,status:d.status||'approved'};}
async function waitForSupportPayment(orderId){let last={paid:false,status:'PENDING',order_id:orderId};for(let i=0;i<5;i++){last=await api(`/api/support/verify?order_id=${encodeURIComponent(orderId)}`);if(last.paid)return last;if(i<4)await new Promise(r=>setTimeout(r,1500));}return last;}
async function donate(){const amount=Number(document.getElementById('rs-amount')?.value||0),phone=String(document.getElementById('rs-phone')?.value||'').replace(/\D/g,''),msg=document.getElementById('rs-donate-msg');if(!state.isAuthenticated){location.hash='#/login?returnTo=%2Freview-support';return;}if(amount<1||amount>100000){msg.textContent='Please enter an amount between ₹1 and ₹1,00,000.';return;}if(!/^\d{10}$/.test(phone)){msg.textContent='Please enter a valid 10-digit phone number.';return;}const button=document.getElementById('rs-donate-btn');if(button)button.disabled=true;msg.textContent='Creating secure payment…';try{const d=await api('/api/support/create-order',{method:'POST',body:JSON.stringify({amount,phone})});if(!d.payment_session_id)throw new Error('Payment session was not created.');await preloadCashfree();const cf=window.Cashfree({mode:d.environment==='PRODUCTION'?'production':'sandbox'});const checkoutResult=await cf.checkout({paymentSessionId:d.payment_session_id,redirectTarget:'_modal'});if(checkoutResult?.error)throw new Error(checkoutResult.error.message||'Payment window could not be opened.');msg.textContent='Verifying payment…';const v=await waitForSupportPayment(d.order_id);if(v.paid){msg.textContent=`Thank you for supporting Bookora ❤️ Transaction: ${d.order_id}`;document.getElementById('rs-amount').value='';document.getElementById('rs-phone').value='';document.querySelectorAll('.rs-amounts button').forEach(x=>x.classList.remove('selected'));}else msg.textContent='Payment is not marked paid yet. If you completed the payment, please wait a moment and try again.';}catch(e){msg.textContent=e.message||'Unable to start payment.';}finally{if(button)button.disabled=false;}}
export async function initReviewSupportEvents(){setRating(5);showAllReviews=false;preloadCashfree().catch(()=>{});document.querySelectorAll('.rs-star-btn').forEach(b=>b.addEventListener('click',()=>setRating(b.dataset.rating)));document.querySelectorAll('.rs-amounts button').forEach(b=>b.addEventListener('click',()=>{document.getElementById('rs-amount').value=b.dataset.amount;document.querySelectorAll('.rs-amounts button').forEach(x=>x.classList.toggle('selected',x===b));}));document.getElementById('rs-review-form')?.addEventListener('submit',async e=>{e.preventDefault();const m=document.getElementById('rs-review-msg');if(!state.isAuthenticated){location.hash='#/login?returnTo=%2Freview-support';return;}const payload={rating:Number(document.getElementById('rs-rating').value),category:document.getElementById('rs-category').value,comment:document.getElementById('rs-comment').value.trim(),publicName:document.getElementById('rs-public').checked};if(payload.comment.length<10){m.textContent='Please write at least 10 characters.';return;}const button=e.submitter||document.querySelector('#rs-review-form .rs-primary');if(button)button.disabled=true;m.textContent='';try{const review=await saveReviewToBackend(payload);state.reviews=[...(Array.isArray(state.reviews)?state.reviews:[]),review];try{sessionStorage.removeItem(REVIEW_CACHE_KEY);}catch(_){}m.textContent='Review saved to Firebase and published instantly. ✓';document.getElementById('rs-comment').value='';await loadReviews();}catch(e){console.error('[Bookora review] Backend Firebase write failed:',e);m.textContent=e.message||'Could not save review to Firebase.';}finally{if(button)button.disabled=false;}});document.getElementById('rs-donate-btn')?.addEventListener('click',donate);loadReviews();}
