import { apiFetch } from '../config.js';
import { state } from '../state.js';
import { updateSEO } from '../utils/seo.js';
import { Toast } from '../components/Toast.js';
let submitting=false;
const v=id=>document.getElementById(id)?.value?.trim()||'';
const c=id=>document.getElementById(id)?.checked===true;
const e=x=>String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
const I=(id,l,t='text',p='',req=true)=>`<div class="sf"><label>${l}${req?' *':''}</label><input id="${id}" type="${t}" placeholder="${e(p)}" ${req?'required':''} autocomplete="off"></div>`;
const S=(id,l,a)=>`<div class="sf"><label>${l} *</label><select id="${id}" required><option value="">Select</option>${a.map(x=>`<option>${e(x)}</option>`).join('')}</select></div>`;
const A=(id,l,p)=>`<div class="sf full"><label>${l} *</label><textarea id="${id}" rows="3" required placeholder="${e(p)}"></textarea></div>`;
const C=(id,t)=>`<label class="sc"><input id="${id}" type="checkbox" required><span>${t}</span></label>`;
export function renderSellerApplyPage(){
 updateSEO({title:'Become a Bookora Seller',description:'Seller onboarding and wallet payout setup.'});
 const st=String(state.currentUser?.seller_status||'none').toLowerCase();
 if(st==='pending')return `<main class="seller-onboard"><div class="seller-card result"><h1>Application Under Review</h1><p>Your seller application has already been submitted.</p><a class="btn btn-primary" href="#/">Back to Bookora</a></div></main>`;
 if(st==='approved')return `<main class="seller-onboard"><div class="seller-card result"><h1>Seller Approved</h1><p>Your seller account is active.</p><a class="btn btn-primary" href="#/seller/dashboard">Seller Dashboard</a></div></main>`;
 return `<main class="seller-onboard"><div class="seller-card"><div class="badge">SELLER ONBOARDING</div><h1>Become a Bookora Seller</h1><p class="intro">Enter your publishing details and wallet payout information once. Bank/PAN details are used for seller payouts and are not shown publicly.</p><form id="seller-onboard-form" novalidate>
 <section><h2>Basic seller details</h2><div class="sg">${I('so-store','Publisher / Store Name','text','Your author or publishing name')}${I('so-legal','Legal / Full Name','text','Your full name')}${I('so-email','Email','email',state.currentUser?.email||'',true)}${I('so-phone','Phone Number','tel','+91 9876543210')}${S('so-type','Publisher Type',['Individual Author','Publisher','Small Publishing House','Educational Publisher'])}${S('so-category','Main Category',['Fiction','Romance','Business','Finance','Education','Technology','Self Help','Productivity','Biography','Children','Health & Wellness','Exam Preparation','Other'])}${S('so-language','Main Publishing Language',['English','Hindi','Marathi','Bengali','Tamil','Telugu','Kannada','Malayalam','Gujarati','Punjabi','Urdu','Other'])}${S('so-format','Ebook Format',['EPUB','PDF','Both EPUB and PDF'])}</div>${A('so-bio','Author / Publishing Bio','Minimum 20 characters.')}${A('so-plan','What do you plan to publish?','Describe the ebooks you plan to publish. Minimum 20 characters.')}${A('so-rights','Rights Declaration','Confirm that you own or have permission to distribute your content.')}</section>
 <section><h2>Wallet & payout details</h2><p class="hint">Required for your seller wallet payout setup. These values are stored server-side and sensitive bank/PAN values are never displayed publicly.</p><div class="sg">${I('so-bank','Bank Name','text','e.g. State Bank of India')}${I('so-holder','Account Holder Name','text','Name exactly as on bank account')}${I('so-account','Bank Account Number','password','Enter account number')}${I('so-ifsc','IFSC Code','text','e.g. SBIN0001234')}${I('so-pan','PAN Number','text','ABCDE1234F')}${I('so-tax','Tax / GST Status','text','e.g. Individual / GST registered')}${I('so-upi','UPI ID','text','Optional payout UPI ID',false)}</div>${A('so-billing','Billing / Registered Address','Address associated with your payout/tax profile.')}</section>
 <section><h2>Declarations</h2><div class="checks">${C('so-copyright','I confirm that I own the copyright or have the necessary rights to publish my content.')}${C('so-original','I confirm that submitted content is original or lawfully licensed.')}${C('so-distribution','I confirm that I have digital distribution rights.')}${C('so-terms','I accept the Bookora Seller Agreement and marketplace rules.')}${C('so-privacy','I acknowledge the Privacy Policy and seller-data processing.')}${C('so-content','I allow Bookora to review submitted content for copyright and policy compliance.')}${C('so-pricing','I accept the seller royalty/commission settings configured by administration.')}</div><button id="so-submit" class="btn btn-primary submit" type="submit">Submit Seller Application</button><div id="so-status" class="status"></div></section>
 </form></div></main><style>.seller-onboard{min-height:85vh;background:var(--bg-secondary);padding:32px 16px 64px}.seller-card{max-width:860px;margin:auto;background:#fff;border:1px solid var(--border-subtle);border-radius:20px;padding:clamp(20px,4vw,40px);box-shadow:var(--shadow-md)}.badge{display:inline-block;padding:6px 10px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:11px;font-weight:800}.seller-card h1{margin:12px 0 8px;color:var(--text-primary)}section{border-top:1px solid #e5e7eb;padding-top:22px;margin-top:22px}section h2{font-size:18px;color:var(--text-primary)}.intro,.hint{color:var(--text-secondary);line-height:1.6}.sg{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.sf label{display:block;font-size:13px;font-weight:700;margin-bottom:6px}.sf input,.sf select,.sf textarea{width:100%;box-sizing:border-box;padding:11px 12px;border:1px solid var(--border-medium);border-radius:10px;background:#fff;font:inherit}.sf.full{margin-top:14px}.checks{display:grid;gap:10px}.sc{display:flex;gap:9px;align-items:flex-start;font-size:13px;line-height:1.45;color:#334155}.submit{width:100%;min-height:48px;margin-top:20px}.status{text-align:center;min-height:24px;margin-top:12px}.result{text-align:center;margin-top:8vh}@media(max-width:680px){.sg{grid-template-columns:1fr}}</style>`;
}
export async function initSellerApplyEvents(){
 const f=document.getElementById('seller-onboard-form');if(!f)return;f.addEventListener('submit',async ev=>{ev.preventDefault();if(submitting)return;if(!f.checkValidity()){f.reportValidity();return;}if(v('so-bio').length<20||v('so-plan').length<20){Toast.error?.('Bio and publishing description must be at least 20 characters.');return;}
 const b=document.getElementById('so-submit'),s=document.getElementById('so-status');submitting=true;b.disabled=true;b.textContent='Submitting…';s.textContent='Saving seller wallet and payout details securely…';
 try{const payload={publisherName:v('so-store'),legalName:v('so-legal'),email:v('so-email'),phone:v('so-phone'),publisherType:v('so-type'),authorBio:v('so-bio'),categories:[v('so-category')],languages:[v('so-language')],publishingDescription:v('so-plan'),ebookFormats:[v('so-format')],rightsDeclaration:v('so-rights'),bankName:v('so-bank'),accountHolderName:v('so-holder'),accountNumber:v('so-account'),ifscCode:v('so-ifsc').toUpperCase(),pan:v('so-pan').toUpperCase(),upiId:v('so-upi'),taxInfoStatus:v('so-tax'),billingAddress:v('so-billing'),copyrightOwner:c('so-copyright'),originalContent:c('so-original'),distributionRights:c('so-distribution'),termsAccepted:c('so-terms'),privacyAccepted:c('so-privacy'),contentRightsAccepted:c('so-content'),pricingAccepted:c('so-pricing'),termsVersion:'1.0',privacyVersion:'1.0',agreementVersion:'1.0'};const r=await apiFetch('/api/seller/apply',{method:'POST',body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch(_){}if(!r.ok||!d.success)throw new Error(d.error||(Array.isArray(d.fields)?d.fields.slice(0,5).join(', '):'Application failed'));state.currentUser={...(state.currentUser||{}),seller_status:'pending',sellerStatus:'inactive'};Toast.success?.('Seller application submitted successfully.');f.innerHTML='<div class="result"><h2>Application Submitted</h2><p>Admin review is pending. Your wallet payout details are saved with the seller account.</p><a class="btn btn-primary" href="#/">Back to Bookora</a></div>';}catch(err){console.error(err);s.textContent=err.message;Toast.error?.(err.message);b.disabled=false;b.textContent='Submit Seller Application';}finally{submitting=false;}});
}
