import { apiFetch } from '../config.js';
import { state } from '../state.js';
import { renderSellerApplyPage } from './SellerApplyQuickPage.js';

const fieldMap={store:'publisherName',legal:'legalName',email:'email',phone:'phone',country:'country',state:'state',city:'city',postal:'postalCode',address:'address',type:'publisherType',books:'previousBooksCount',website:'website',portfolio:'portfolioUrl',bio:'authorBio',category:'categories',language:'languages',catalogue:'publishingDescription',format:'ebookFormats',imprint:'imprintName',isbn:'isbnPreference',drm:'drmPreference',ai:'aiContentDisclosure',sample:'sampleAvailability',accessibility:'accessibilityInfo',rights:'rightsDeclaration',copyright:'copyrightOwner',original:'originalContent',distribution:'distributionRights',payout:'payoutMethod',bank:'bankName',holder:'accountHolderName',account:'accountNumber',ifsc:'ifscCode',upi:'upiId',pan:'pan',tax:'taxInfoStatus',billing:'billingAddress',terms:'termsAccepted',privacy:'privacyAccepted',content:'contentRightsAccepted',pricing:'pricingAccepted'};
const stepFields={1:['store','legal','email','phone','country','state','city','postal','address','type','books','website','portfolio'],2:['bio','category','language','catalogue','format','imprint','isbn','drm','ai','sample','accessibility'],3:['rights','copyright','original','distribution'],4:['payout','bank','holder','account','ifsc','upi','pan','tax','billing'],5:['terms','privacy','content','pricing']};
const id=k=>`s-${k}`;
const val=k=>document.getElementById(id(k))?.value?.trim()||'';
const collect=step=>{const p={step};for(const k of stepFields[step]||[]){const e=document.getElementById(id(k));if(!e)continue;p[fieldMap[k]]=e.type==='checkbox'?e.checked:(e.value?.trim()||'');if(['categories','languages','ebookFormats'].includes(fieldMap[k]))p[fieldMap[k]]=p[fieldMap[k]]?[p[fieldMap[k]]]:[];}return p;};
const validate=step=>{const panel=document.querySelector(`.panel[data-panel="${step}"]`);if(!panel)return false;for(const e of panel.querySelectorAll('[required]'))if(!e.checkValidity()){e.reportValidity();return false;}if(step===2&&(val('bio').length<20||val('catalogue').length<20)){window.Toast?.error?.('Bio and planned catalogue must each be at least 20 characters.');return false;}return true;};
const save=async(step)=>{const s=document.getElementById('seller-status');if(s)s.textContent=`Saving Step ${step} to Firebase…`;const r=await apiFetch('/api/seller/application-progress',{method:'POST',body:JSON.stringify(collect(step))});let d={};try{d=await r.json();}catch(_){}if(!r.ok||!d.success)throw new Error(d.error||`Step ${step} could not be saved`);if(s)s.textContent=`Step ${step} saved ✓`;};
const restore=async()=>{try{const r=await apiFetch('/api/seller/application-progress',{method:'GET'});if(!r.ok)return 1;const d=await r.json(),a=d.application||{};for(const k of Object.keys(fieldMap)){const e=document.getElementById(id(k));if(!e||a[fieldMap[k]]===undefined||a[fieldMap[k]]===null)continue;e.type==='checkbox'?e.checked=!!a[fieldMap[k]]:e.value=Array.isArray(a[fieldMap[k]])?(a[fieldMap[k]][0]||''):a[fieldMap[k]];}const n=Number(a.onboardingStep);return n>=1&&n<=5?n:1;}catch(e){console.warn('[Bookora seller draft restore]',e);return 1;}};
const show=step=>{document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',+x.dataset.panel===step));document.querySelectorAll('.step').forEach(x=>{const n=+x.dataset.ind;x.classList.toggle('active',n===step);x.classList.toggle('done',n<step);});const back=document.getElementById('back-step'),next=document.getElementById('next-step');if(back)back.disabled=step===1;if(next)next.style.display=step===5?'none':'inline-block';if(step===5){const n=document.getElementById('r-name'),p=document.getElementById('r-payout'),f=document.getElementById('r-format');if(n)n.textContent=val('store')||'—';if(p)p.textContent=val('bank')?`${val('bank')} • ${val('ifsc')||'IFSC pending'}`:'—';if(f)f.textContent=val('format')||'—';}window.scrollTo({top:0,behavior:'smooth'});};
const stripImageUI=html=>{let out=String(html||'');const start=out.indexOf('<div class="profile-box">');if(start>=0){const end=out.indexOf('</section>',start);if(end>=0)out=out.slice(0,start)+out.slice(end);}out=out.replace(/\s*<div><b>Profile<\/b><span id="r-image">[^<]*<\/span><\/div>/,'');out=out.replace('publisher details and profile image.','identity, address and publisher details.');return out;};
const install=async()=>{const form=document.getElementById('seller-five-form');if(!form||form.dataset.firebaseStableNoImage==='1')return;form.dataset.firebaseStableNoImage='1';let current=await restore();
 const next0=document.getElementById('next-step');const next=next0?.cloneNode(true);if(next0&&next){next0.replaceWith(next);next.addEventListener('click',async()=>{if(next.dataset.busy==='1'||!validate(current))return;next.dataset.busy='1';next.disabled=true;next.textContent='Saving…';try{await save(current);if(current<5){current++;show(current);}}catch(e){document.getElementById('seller-status').textContent=e.message;window.Toast?.error?.(e.message);}finally{next.dataset.busy='0';next.disabled=false;next.textContent='Save & Continue →';}});}
 const back0=document.getElementById('back-step');const back=back0?.cloneNode(true);if(back0&&back){back0.replaceWith(back);back.addEventListener('click',()=>{if(current>1){current--;show(current);}});}
 document.getElementById('account-eye')?.addEventListener('click',()=>{const a=document.getElementById('s-account');if(a)a.type=a.type==='password'?'text':'password';});
 form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(current!==5||form.dataset.submitting==='1'||!validate(5))return;form.dataset.submitting='1';const b=document.getElementById('seller-submit'),s=document.getElementById('seller-status');if(b){b.disabled=true;b.textContent='Submitting securely…';}try{await save(5);const r=await apiFetch('/api/seller/apply',{method:'POST',body:JSON.stringify({...collect(1),...collect(2),...collect(3),...collect(4),...collect(5)})});let d={};try{d=await r.json();}catch(_){}if(!r.ok||!d.success)throw new Error(d.error||'Application failed');state.currentUser={...(state.currentUser||{}),seller_status:'pending',sellerStatus:'inactive'};if(s) s.textContent='Application submitted ✓';form.innerHTML='<div class="result"><div class="result-icon">✓</div><h2>Application Submitted</h2><p>All 5 steps were saved to Firebase and your application is now pending admin review.</p><a class="btn btn-primary" href="#/">Back to Bookora</a></div>';}catch(e){if(s)s.textContent=e.message||'Application failed';window.Toast?.error?.(e.message||'Application failed');form.dataset.submitting='';if(b){b.disabled=false;b.textContent='Submit Seller Application for Review';}}});
 show(current);};
export async function renderStable(){return stripImageUI(renderSellerApplyPage());}
export async function initStable(){await install();}
