import { apiFetch } from '../config.js';
import { state } from '../state.js';
import { renderSellerApplyPage, initSellerApplyEvents } from './SellerApplyQuickPage.js';

const fieldMap={
  store:'publisherName',legal:'legalName',email:'email',phone:'phone',country:'country',state:'state',city:'city',postal:'postalCode',address:'address',type:'publisherType',books:'previousBooksCount',website:'website',portfolio:'portfolioUrl',bio:'authorBio',category:'categories',language:'languages',catalogue:'publishingDescription',format:'ebookFormats',imprint:'imprintName',isbn:'isbnPreference',drm:'drmPreference',ai:'aiContentDisclosure',sample:'sampleAvailability',accessibility:'accessibilityInfo',rights:'rightsDeclaration',copyright:'copyrightOwner',original:'originalContent',distribution:'distributionRights',payout:'payoutMethod',bank:'bankName',holder:'accountHolderName',account:'accountNumber',ifsc:'ifscCode',upi:'upiId',pan:'pan',tax:'taxInfoStatus',billing:'billingAddress',terms:'termsAccepted',privacy:'privacyAccepted',content:'contentRightsAccepted',pricing:'pricingAccepted'
};
const stepFields={1:['store','legal','email','phone','country','state','city','postal','address','type','books','website','portfolio'],2:['bio','category','language','catalogue','format','imprint','isbn','drm','ai','sample','accessibility'],3:['rights','copyright','original','distribution'],4:['payout','bank','holder','account','ifsc','upi','pan','tax','billing'],5:['terms','privacy','content','pricing']};
const id=k=>`s-${k}`;
const val=k=>document.getElementById(id(k))?.value?.trim()||'';
const collect=step=>{const p={step};for(const k of stepFields[step]||[]){const e=document.getElementById(id(k));if(!e)continue;p[fieldMap[k]]=e.type==='checkbox'?e.checked:(e.value?.trim()||'');}const photo=state.currentUser?.photoURL||state.currentUser?.photoUrl||state.currentUser?.photo_url||'';if(photo)p.profileImageUrl=photo;p.profileImageSource='bookora-account';return p;};
const validate=step=>{const panel=document.querySelector(`.panel[data-panel="${step}"]`);if(!panel)return false;for(const e of panel.querySelectorAll('[required]'))if(!e.checkValidity()){e.reportValidity();return false;}return true;};
const save=async(step)=>{const s=document.getElementById('seller-status');if(s)s.textContent=`Saving Step ${step} to Firebase…`;const r=await apiFetch('/api/seller/application-progress',{method:'POST',body:JSON.stringify(collect(step))});let d={};try{d=await r.json();}catch(_){}if(!r.ok||!d.success)throw new Error(d.error||`Step ${step} could not be saved`);if(s)s.textContent=`Step ${step} saved ✓`;};
const show=step=>{document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',+x.dataset.panel===step));document.querySelectorAll('.step').forEach(x=>{const n=+x.dataset.ind;x.classList.toggle('active',n===step);x.classList.toggle('done',n<step);});const back=document.getElementById('back-step');const next=document.getElementById('next-step');if(back)back.disabled=step===1;if(next)next.style.display=step===5?'none':'inline-block';if(step===5){const n=document.getElementById('r-name');if(n)n.textContent=val('store')||'—';const i=document.getElementById('r-image');if(i)i.textContent='Using account photo ✓';const p=document.getElementById('r-payout');if(p)p.textContent=val('bank')?`${val('bank')} • ${val('ifsc')||'IFSC pending'}`:'—';const f=document.getElementById('r-format');if(f)f.textContent=val('format')||'—';}window.scrollTo({top:0,behavior:'smooth'});};
const install=async()=>{const form=document.getElementById('seller-five-form');if(!form||form.dataset.firebaseStable==='1')return;if(typeof initSellerApplyEvents==='function')await initSellerApplyEvents();form.dataset.firebaseStable='1';
  const next0=document.getElementById('next-step');const back0=document.getElementById('back-step');
  const next=next0?.cloneNode(true);if(next0&&next){next0.replaceWith(next);next.addEventListener('click',async()=>{const step=+[...document.querySelectorAll('.panel')].find(x=>x.classList.contains('active'))?.dataset.panel||1;if(!validate(step))return;next.disabled=true;try{await save(step);if(step<5)show(step+1);}catch(e){const s=document.getElementById('seller-status');if(s)s.textContent=e.message;window.Toast?.error?.(e.message);}finally{next.disabled=false;}});}
  const back=back0?.cloneNode(true);if(back0&&back){back0.replaceWith(back);back.addEventListener('click',()=>{const step=+[...document.querySelectorAll('.panel')].find(x=>x.classList.contains('active'))?.dataset.panel||1;if(step>1)show(step-1);});}
  form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(form.dataset.submitting==='1'||!validate(5))return;form.dataset.submitting='1';const b=document.getElementById('seller-submit');const s=document.getElementById('seller-status');if(b){b.disabled=true;b.textContent='Submitting securely…';}try{await save(5);const r=await apiFetch('/api/seller/apply',{method:'POST',body:JSON.stringify({...collect(1),...collect(2),...collect(3),...collect(4),...collect(5)})});let d={};try{d=await r.json();}catch(_){}if(!r.ok||!d.success)throw new Error(d.error||'Application failed');state.currentUser={...(state.currentUser||{}),seller_status:'pending',sellerStatus:'inactive'};if(s) s.textContent='Application submitted ✓';form.innerHTML='<div class="result"><div class="result-icon">✓</div><h2>Application Submitted</h2><p>All 5 steps were saved to Firebase and your application is now pending admin review.</p><a class="btn btn-primary" href="#/">Back to Bookora</a></div>';}catch(e){if(s)s.textContent=e.message||'Application failed';if(b){b.disabled=false;b.textContent='Submit Seller Application for Review';}form.dataset.submitting='';}},true);
};
export async function renderStable(){return renderSellerApplyPage();}
export async function initStable(){await install();const active=+[...document.querySelectorAll('.panel')].find(x=>x.classList.contains('active'))?.dataset.panel||1;show(active);}
